
let score=0, solved=0, total=5, questions=[], tries=[], done=[];
const url=new URL(window.location.href); const typ=url.searchParams.get('typ')||'startklar';
const n=Number(url.searchParams.get('n')); if(Number.isInteger(n)&&n>0&&n<=20) total=n;
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a} function sum1(n){return n*(n+1)/2}
function norm(s){return String(s).toLowerCase().replaceAll(' ','').replaceAll('·','*').replaceAll('−','-').replaceAll('²','^2')}
function match(v,a){if(Array.isArray(a))return a.some(x=>match(v,x)); if(typeof a==='number')return Number(v)===a; return norm(v)===norm(a)}
function form(a,b,c){let p=[]; if(a)p.push(a==1?'x²':a==-1?'-x²':a+'x²'); if(b){let s=b>0&&p.length?' + ':b<0?' - ':''; p.push(s+(Math.abs(b)==1?'x':Math.abs(b)+'x'))} if(c){let s=c>0&&p.length?' + ':c<0?' - ':''; p.push(s+Math.abs(c))} return p.join('')||'0'}
function genFigurKreuz(){let n=rand(8,18);return{source:'Startklar · Figurenzahlen',text:'Eine Kreuzfigur wächst: Figur 1 hat 5 Kreise, Figur 2 hat 9, Figur 3 hat 13.',ask:`Wie viele Kreise hat Figur ${n}?`,answer:4*n+1,hint1:'Von Figur zu Figur kommen immer 4 Kreise dazu.',hint2:`Term: 4n+1. Setze n=${n} ein.`,solution:`4·${n}+1=${4*n+1}`}}
function genFigurQuadrat(){let n=rand(6,18);return{source:'LK · Quadratmuster',text:'Ein Quadratmuster wird durch den Term n² + 4n beschrieben.',ask:`Wie viele Quadrate hat Figur ${n}?`,answer:n*n+4*n,hint1:'Setze die Figurnummer für n ein.',hint2:`Rechne ${n}²+4·${n}.`,solution:`${n*n}+${4*n}=${n*n+4*n}`}}
function genWuerfel(){let n=rand(5,15);return{source:'Test · Würfelfolge',text:'Eine Würfelfolge hat die Anzahlen 3, 7, 13, 21, …',ask:`Wie viele Würfel hat Schritt ${n}?`,answer:n*n+n+1,hint1:'Die Zuwächse sind 4, 6, 8, 10, …',hint2:'Passender Term: n²+n+1.',solution:`${n}²+${n}+1=${n*n+n+1}`}}
function genLinear(){let d=rand(3,7),c=rand(-9,6),vals=[1,2,3,4].map(n=>d*n+c),n=[20,50,100,150][rand(0,3)],ans=d*n+c;let term=c>=0?`${d}x+${c}`:`${d}x${c}`;return{source:'Zahlenfolge · linearer Term',text:`x=1,2,3,4 → Tₓ=${vals.join(', ')}`,ask:`Welcher Wert gehört zu x=${n}?`,answer:ans,hint1:'Finde zuerst die konstante Differenz.',hint2:`Differenz +${d}; Term ${term}.`,solution:`T_${n}=${d}·${n}${c>=0?'+':'-'}${Math.abs(c)}=${ans}`}}
function genQuadratisch(){let a=rand(1,2),b=rand(-2,6),c=rand(-7,5),vals=[1,2,3,4].map(n=>a*n*n+b*n+c),n=[10,20,50][rand(0,2)],ans=a*n*n+b*n+c,term=form(a,b,c);return{source:'Zahlenfolge · quadratischer Term',text:`x=1,2,3,4 → Tₓ=${vals.join(', ')}`,ask:`Berechne T_${n}.`,answer:ans,hint1:'Die Differenz wächst selbst regelmässig.',hint2:`Term: ${term}. Setze x=${n} ein.`,solution:`${term} ergibt ${ans}`}}
function genGauss(){let n=rand(40,180);return{source:'Summe · Gauß-Idee',text:`Berechne geschickt: 1+2+3+…+${n}`,ask:'Wie gross ist die Summe?',answer:sum1(n),hint1:'Paarweise addieren: erste + letzte Zahl.',hint2:`Formel: n(n+1)/2 = ${n}·${n+1}/2.`,solution:`${n}·${n+1}/2=${sum1(n)}`}}
function genGaussDiff(){let a=rand(120,300),b=rand(2,15),c=rand(18,40),ans=sum1(a)-(sum1(c)-sum1(b-1));return{source:'Test · Summendifferenz',text:`Summe 1 bis ${a} minus Summe ${b} bis ${c}.`,ask:'Wie gross ist die Differenz?',answer:ans,hint1:'Berechne zuerst beide Summen getrennt.',hint2:`Summe ${b} bis ${c}=S_${c}-S_${b-1}.`,solution:`${sum1(a)}-(${sum1(c)}-${sum1(b-1)})=${ans}`}}
function genGleichung(){let x=rand(3,18),a=rand(2,8),b=rand(-12,12),rhs=a*x+b;return{source:'Gleichung',text:`Löse: ${a}x ${b>=0?'+':'-'} ${Math.abs(b)} = ${rhs}`,ask:'Wie lautet x?',answer:x,hint1:'Zuerst die Zahl ohne x auf die andere Seite bringen.',hint2:`Danach durch ${a} teilen.`,solution:`${a}x=${rhs-b}; x=${x}`}}
function genUngleichung(){let g=rand(3,15),a=rand(2,6),b=rand(-8,8),rhs=a*g+b;return{source:'Ungleichung',text:`Löse in ℕ: ${a}x ${b>=0?'+':'-'} ${Math.abs(b)} ≤ ${rhs}`,ask:'Gib die grösste mögliche natürliche Zahl x an.',answer:g,hint1:'Wie bei einer Gleichung umformen.',hint2:`Es ergibt sich x≤${g}.`,solution:`Grösste natürliche Lösung: ${g}`}}
function genFakt(){let t=rand(1,3); if(t==1){let a=rand(2,8),b=rand(2,9);return{source:'Faktorisieren',text:`Faktorisiere: ${a}x + ${a*b}`,ask:'Faktorisierte Form:',answer:[`${a}(x+${b})`,`${a}*(x+${b})`],hint1:'Suche den gemeinsamen Faktor.',hint2:`Beide Terme sind durch ${a} teilbar.`,solution:`${a}(x+${b})`}} if(t==2){let a=rand(2,9);return{source:'Faktorisieren · Binom',text:`Faktorisiere: x² + ${2*a}x + ${a*a}`,ask:'Faktorisierte Form:',answer:[`(x+${a})^2`,`(x+${a})(x+${a})`],hint1:'Das ist ein quadratisches Binom.',hint2:`Gesucht ist (x+${a})².`,solution:`(x+${a})²`}} let a=rand(2,9);return{source:'Faktorisieren · Differenz',text:`Faktorisiere: x² - ${a*a}`,ask:'Faktorisierte Form:',answer:[`(x-${a})(x+${a})`,`(x+${a})(x-${a})`],hint1:'Differenz von Quadraten.',hint2:`x²-${a*a}=x²-${a}².`,solution:`(x-${a})(x+${a})`}}
function genTextgl(){let x=rand(3,12),a=rand(2,5),b=rand(2,8),c=rand(2,6),r=a*x+b-c*x;return{source:'Textgleichung',text:`Addiert man zum ${a}-Fachen einer Zahl ${b}, so erhält man ${r} mehr als das ${c}-Fache der Zahl.`,ask:'Welche Zahl ist gesucht?',answer:x,hint1:'Setze für die gesuchte Zahl x.',hint2:`Gleichung: ${a}x+${b}=${c}x+${r}`,solution:`x=${x}`}}
const pools={
startklar:{title:'Startklar · Vom Bild zum Term',info:'Terme, Figurenzahlen, Gauß-Summe, lineare und quadratische Folgen.',generators:[genFigurKreuz,genGauss,genLinear,genQuadratisch,genGleichung]},
lk:{title:'Lernkontrolle · Vom Bild zum Term',info:'Gleichung, Ungleichung, Summen, Folgen und Figur-Terme.',generators:[genGleichung,genUngleichung,genGauss,genLinear,genQuadratisch,genFigurQuadrat]},
test:{title:'Test · Vom Bild zum Term',info:'Gleichungen, Faktorisieren, Folgen, Würfelmuster, Summendifferenz und Textgleichungen.',generators:[genGleichung,genUngleichung,genFakt,genLinear,genQuadratisch,genWuerfel,genGaussDiff,genTextgl]},
'figur-kreuz':{title:'Repetition · Figurenzahlen',info:'Kreuz-/Kreisfiguren wie in Startklar.',generators:[genFigurKreuz]},'figur-quadrat':{title:'Repetition · Quadratmuster',info:'Figur-Terme vom Typ n²+4n.',generators:[genFigurQuadrat]},wuerfel:{title:'Repetition · Würfelfolge',info:'Würfelmuster mit quadratischem Term.',generators:[genWuerfel]},'gauss-summe':{title:'Repetition · Gauß-Summe',info:'Summen von 1 bis n geschickt berechnen.',generators:[genGauss]},'gauss-differenz':{title:'Repetition · Summendifferenz',info:'Differenz zweier Summen wie im Test.',generators:[genGaussDiff]},'linear-folge':{title:'Repetition · Lineare Folge',info:'Lineare Zahlenfolgen und Term Tₓ.',generators:[genLinear]},'quadratisch-folge':{title:'Repetition · Quadratische Folge',info:'Quadratische Folgen mit Term.',generators:[genQuadratisch]},gleichung:{title:'Repetition · Gleichung',info:'Lineare Gleichungen lösen.',generators:[genGleichung]},ungleichung:{title:'Repetition · Ungleichung',info:'Ungleichungen in natürlichen Zahlen.',generators:[genUngleichung]},faktorisieren:{title:'Repetition · Faktorisieren',info:'Ausklammern, Binome, Differenz von Quadraten.',generators:[genFakt]},textgleichung:{title:'Repetition · Textgleichung',info:'Text in Gleichung übersetzen und lösen.',generators:[genTextgl]}
};
function choose(){let p=pools[typ]||pools.startklar;return p.generators[rand(0,p.generators.length-1)]}
function newTest(){let p=pools[typ]||pools.startklar; pageTitle.innerText=p.title; pageSub.innerText='adaptive Nachbearbeitung'; trainerTitle.innerText=p.title; trainerInfo.innerText=p.info; score=0;solved=0;questions=[];tries=Array(total).fill(0);done=Array(total).fill(false);aufgaben.innerHTML='';result.style.display='none';bar.style.width='0%'; for(let i=0;i<total;i++){let q=choose()();questions.push(q);aufgaben.innerHTML+=`<div class="card"><div class="meta">${q.source}</div><h3>Übung ${i+1}</h3><p class="question">${q.text}</p><p>${q.ask}</p><input id="input${i}" type="text" autocomplete="off"><br><button id="btn${i}" onclick="check(${i})">Überprüfen</button><p id="feedback${i}"></p></div>`}}
function check(i){if(done[i])return;let input=document.getElementById('input'+i),btn=document.getElementById('btn'+i),feedback=document.getElementById('feedback'+i),q=questions[i]; if(input.value.trim()===''){feedback.innerHTML='<span class="fail">Bitte zuerst eine Antwort eingeben.</span>';return} if(match(input.value,q.answer)){done[i]=true;solved++;if(tries[i]===0)score++;feedback.innerHTML='<span class="ok">✅ Richtig!</span>';input.disabled=true;btn.disabled=true}else{tries[i]++; if(tries[i]===1)feedback.innerHTML='<span class="fail">❌ Noch nicht.</span><br><span class="hint">💡 Tipp 1:</span> '+q.hint1; else if(tries[i]===2)feedback.innerHTML='<span class="fail">❌ Noch nicht.</span><br><span class="hint">💡 Tipp 2:</span> '+q.hint2; else feedback.innerHTML='<span class="fail">❌ Noch nicht.</span><br>✅ '+q.solution+'<br>Du kannst die richtige Antwort trotzdem noch eintippen.';input.focus();input.select()} bar.style.width=(solved/total*100)+'%'; if(solved===total){let stars=score>=Math.ceil(total*.9)?'⭐⭐⭐':score>=Math.ceil(total*.6)?'⭐⭐':'⭐';result.style.display='block';result.innerHTML='🏁 Training abgeschlossen!<br><br>'+stars+'<br><br>'+score+' von '+total+' Aufgaben beim ersten Versuch richtig.'}}
window.onload=newTest;
